// Code generated by "stringer -type=Gear -trimprefix=Gear"; DO NOT EDIT.

package unit

import "strconv"

const _Gear_name = "ParkNeutralReverseDriveNotAvailableError"

var _Gear_index = [...]uint8{0, 4, 11, 18, 23, 35, 40}

func (i Gear) String() string {
	if i >= Gear(len(_Gear_index)-1) {
		return "Gear(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gear_name[_Gear_index[i]:_Gear_index[i+1]]
}
